### ISSUE TITLE
sync ve async programlama nedir?

### ISSUE THREAD

**Issue by mbozkaya** [ismailhasir/react-dotnet-casestudy#2]

**Comment by ismailhasir** [comment]
[JSON.pdf](https://github.com/ismailhasir/react-dotnet-casestudy/files/7758023/JSON.pdf)

**Comment by ismailhasir** [comment]
[Asynchoronous_Code.pdf](https://github.com/ismailhasir/react-dotnet-casestudy/files/7758025/Asynchoronous_Code.pdf)
